[package]
name = "prkserver"
version = "0.1.0"
edition = "2021"

[dependencies]
# clap = { version = "4.5.4", features = ["cargo"] }
# dialoguer = "0.11.0"
# fs_extra = "1.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.14"
# tokio = { version = "1", features = ["full"] }
include_dir = "0.7.3"
convert_case = "0.6.0"
