project_name = "todo_app"
database_url = "mysql://root:passowrd@localhost/todo_app"
database_type = "mysql"

[[models]]
name = "User"
table_name = "users"
fields = [
    { name = "id", type = "i32" },
    { name = "username", type = "String" },
    { name = "email", type = "String" },
]
endpoints = [
    { method = "GET", path = "/users" },
    { method = "POST", path = "/users" },
]


[[models]]
name = "Todo"
table_name = "todos"
fields = [
    { name = "id", type = "i32" },
    { name = "task", type = "String" },
    { name = "description", type = "Option<String>" },
]
endpoints = [
    { method = "GET", path = "/todos" },
    { method = "GET", path = "/todos/:id" },
]
